[versions]
plugin_architectury = "3.4-SNAPSHOT"
plugin_loom = "1.4-SNAPSHOT"
plugin_cf = "2.1"
plugin_shadow = "8.+"
plugin_publish_all = "0.+"

[plugins]
architectury-plugin = { id = "architectury-plugin", version.ref = "plugin_architectury" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "plugin_loom" }
cf = { id = "com.kotori316.plugin.cf", version.ref = "plugin_cf" }
