modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Kotori316/FluidTank2/issues"
license = "All rights reserved"

[[mods]]
modId = "fluidtank"
version = "${version}"
displayName = "Fluid Tank"
displayURL = "https://github.com/Kotori316/FluidTank2"
modUrl = "https://github.com/Kotori316/FluidTank2"
updateJSONURL = "${update_url}"
credits = "Kotori316"
authors = "Kotori316"
description = '''
FluidTank
'''
logoFile = "assets/fluidtank/textures/icon.png"

[[dependencies.fluidtank]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.70-beta, )"
ordering = "NONE"
side = "BOTH"
