name: Java CI

on:
  push:
    branches: [ "1.20" ]
  pull_request:
    branches: [ "1.20" ]

permissions:
  contents: read

jobs:
  assemble:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          gradle-home-cache-cleanup: true
      - run: ./gradlew javaToolchains assemble --scan
      - run: ./gradlew checkChangelog
      - run: ./gradlew checkReleaseVersion
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FluidTank2-${{ github.run_number }}
          path: "*/build/libs/*.jar"
          if-no-files-found: error
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform: [ common, forge, fabric, neoforge ]
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          gradle-home-cache-cleanup: true
      - name: ${{ matrix.platform }} JUnit
        run: ./gradlew :${{ matrix.platform }}:test
        env:
          RUN_JUNIT: true
      - name: ${{ matrix.platform }} GameTest
        if: ${{ matrix.platform != 'common' }}
        timeout-minutes: 5
        run: ./gradlew :${{ matrix.platform }}:runGameTest
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          RUN_GAME_TEST: true

  forge-data-gen:
    runs-on: ubuntu-latest
    env:
      DISABLE_FORGE: false
      DISABLE_FABRIC: true
      DISABLE_NEOFORGE: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          gradle-home-cache-cleanup: true
      - name: Compile
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :forge:genDataClasses
      - name: Prepare Run
        run: >-
          ./gradlew configureLaunch downloadAssets ||
          (sleep 5 && ./gradlew configureLaunch downloadAssets) ||
          (sleep 5 && ./gradlew configureLaunch downloadAssets)
      - name: Check assets file
        run: ./gradlew checkResourceFiles
      - name: Forge DataGen
        run: ./gradlew :forge:runData
        timeout-minutes: 5
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: Check updated files
        run: git status
      - name: Check diff
        run: git diff

  merge-checker:
    if: always()
    needs:
      - assemble
      - test
    uses: 'Kotori316/common-script/.github/workflows/merge-checker.yaml@main'
    with:
      needs: ${{ toJSON(needs) }}
