name: Release
on:
  workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: true
      - name: Check Release Version
        run: ./gradlew checkReleaseVersion
        env:
          RELEASE_DEBUG: false
      - name: Compile
        run: ./gradlew testClasses
      - name: JUnit
        run: ./gradlew test
        env:
          RUN_JUNIT: true
      - name: Prepare GameTest
        run: |
          (./gradlew configureLaunch downloadAssets) || \
            (sleep 5 && ./gradlew configureLaunch downloadAssets) || \
            (sleep 5 && ./gradlew configureLaunch downloadAssets) || true
      - name: GameTest
        run: ./gradlew runGameTest
        env:
          RUN_GAME_TEST: true

  release:
    needs: [ check ]
    permissions:
      id-token: write
      contents: write
      packages: write
    # See https://github.com/Kotori316/common-script/blob/main/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@main'
    with:
      sign_check_command: 'assemble publishToMavenLocal'
      release_command: 'assemble publishToMavenLocal githubRelease publishMods registerVersion publish --continue'
      enable_signature_check: true
    secrets: inherit
